### ISSUE TITLE
Composer not being able to download zipball after repo owner change

### ISSUE THREAD

**Issue by rootpd** [phpunit/phpunit-story#14]
There probably was a change in repository recently (sebastianbergmann/phpunit-story -> phpunit/phpunit-story), but the packagist configuration is pointing to the old repo.

```
  - Installing phpunit/phpunit-story (1.0.2)
    Downloading: connection...    Failed to download phpunit/phpunit-story from dist: The "https://api.github.com/repos/sebastianbergmann/phpunit-story/zipball/092d49c13ecb3becf89717988916c53db92d096e" file could not be downloaded (HTTP/1.1 404 Not Found)
    Now trying to download from source
  - Installing phpunit/phpunit-story (1.0.2)
    Cloning 092d49c13ecb3becf89717988916c53db92d096e
```

The problem is that composer is trying to download zipball from old repository and API is throwing 404. I think you need to update packagist (https://packagist.org/packages/phpunit/phpunit-story) URLs (canonical, sources...) to the new repo too.

Without that, I'm only able to download repo if my public key (and all my coworker's) is added at github. Which we don't really want.

Thanks.

**Comment by sebastianbergmann** [comment]
Fixed.
